import { User, CartItem, Order, Product, Review } from './types'

const STORAGE_KEYS = {
  USER: 'flowers_user',
  CART: 'flowers_cart',
  ORDERS: 'flowers_orders',
  WISHLIST: 'flowers_wishlist',
  PRODUCTS: 'flowers_products',
  REVIEWS: 'flowers_reviews',
}

export const storage = {
  // User
  getUser: (): User | null => {
    if (typeof window === 'undefined') return null
    const data = localStorage.getItem(STORAGE_KEYS.USER)
    return data ? JSON.parse(data) : null
  },

  setUser: (user: User | null): void => {
    if (typeof window === 'undefined') return
    if (user) {
      localStorage.setItem(STORAGE_KEYS.USER, JSON.stringify(user))
    } else {
      localStorage.removeItem(STORAGE_KEYS.USER)
    }
  },

  // Cart
  getCart: (): CartItem[] => {
    if (typeof window === 'undefined') return []
    const data = localStorage.getItem(STORAGE_KEYS.CART)
    return data ? JSON.parse(data) : []
  },

  setCart: (cart: CartItem[]): void => {
    if (typeof window === 'undefined') return
    localStorage.setItem(STORAGE_KEYS.CART, JSON.stringify(cart))
  },

  addToCart: (item: CartItem): void => {
    const cart = storage.getCart()
    const existingIndex = cart.findIndex(
      (i) => i.product.id === item.product.id
    )
    if (existingIndex >= 0) {
      cart[existingIndex].quantity += item.quantity
    } else {
      cart.push(item)
    }
    storage.setCart(cart)
  },

  removeFromCart: (productId: string): void => {
    const cart = storage.getCart()
    const filtered = cart.filter((item) => item.product.id !== productId)
    storage.setCart(filtered)
  },

  updateCartItemQuantity: (productId: string, quantity: number): void => {
    const cart = storage.getCart()
    const item = cart.find((i) => i.product.id === productId)
    if (item) {
      if (quantity <= 0) {
        storage.removeFromCart(productId)
      } else {
        item.quantity = quantity
        storage.setCart(cart)
      }
    }
  },

  clearCart: (): void => {
    if (typeof window === 'undefined') return
    localStorage.removeItem(STORAGE_KEYS.CART)
  },

  // Orders
  getOrders: (): Order[] => {
    if (typeof window === 'undefined') return []
    const data = localStorage.getItem(STORAGE_KEYS.ORDERS)
    return data ? JSON.parse(data) : []
  },

  addOrder: (order: Order): void => {
    const orders = storage.getOrders()
    orders.unshift(order)
    localStorage.setItem(STORAGE_KEYS.ORDERS, JSON.stringify(orders))
  },

  // Wishlist
  getWishlist: (): string[] => {
    if (typeof window === 'undefined') return []
    const data = localStorage.getItem(STORAGE_KEYS.WISHLIST)
    return data ? JSON.parse(data) : []
  },

  toggleWishlist: (productId: string): void => {
    const wishlist = storage.getWishlist()
    const index = wishlist.indexOf(productId)
    if (index >= 0) {
      wishlist.splice(index, 1)
    } else {
      wishlist.push(productId)
    }
    localStorage.setItem(STORAGE_KEYS.WISHLIST, JSON.stringify(wishlist))
  },

  // Products (mock data)
  getProducts: (): Product[] => {
    if (typeof window === 'undefined') return []
    const data = localStorage.getItem(STORAGE_KEYS.PRODUCTS)
    const version = localStorage.getItem('flowers_products_version')
    // Если версия не совпадает или данных нет, обновить товары
    if (!data || version !== '4') {
      // Очистить старые данные
      if (data) {
        localStorage.removeItem(STORAGE_KEYS.PRODUCTS)
      }
    } else {
      return JSON.parse(data)
    }
    
    // Initialize with mock data
    const mockProducts: Product[] = [
      // Bouquets
      {
        id: '1',
        name: 'Букет белых цветов',
        price: 86,
        image: '🌼',
        category: 'Bouquets',
        occasion: ['Birthday', 'Anniversary'],
        flowers: ['Roses', 'Lilies'],
        rating: 4.9,
        reviewsCount: 15,
        description: 'Красивые белые цветы, собранные в элегантный букет.',
        seller: 'Флорист Яков',
        size: 'Medium',
      },
      {
        id: '5',
        name: 'Сине-белый букет',
        price: 90,
        image: '💐',
        category: 'Bouquets',
        occasion: ['Wedding', 'Anniversary'],
        flowers: ['Tulips', 'Hyacinths'],
        rating: 4.9,
        reviewsCount: 107,
        description: 'Элегантный сине-белый букет, идеальный для особых случаев.',
        seller: 'Флорист Яков',
        size: 'Boutique',
      },
      {
        id: '6',
        name: 'Королевский розовый букет',
        price: 95,
        image: '🌹',
        category: 'Bouquets',
        occasion: ['Valentine', 'Anniversary'],
        flowers: ['Roses', 'Peonies'],
        rating: 4.8,
        reviewsCount: 84,
        description: 'Романтичный розовый букет с премиум розами.',
        seller: 'Радужные Розы',
        size: 'Boutique',
      },
      {
        id: '7',
        name: 'Букет "Закат"',
        price: 110,
        image: '🌺',
        category: 'Bouquets',
        occasion: ['Birthday', 'Graduation'],
        flowers: ['Sunflowers', 'Daisies'],
        rating: 4.7,
        reviewsCount: 52,
        description: 'Яркий и жизнерадостный букет с подсолнухами и ромашками.',
        seller: 'Лилейная Аллея',
        size: 'Large',
      },
      // Indoor Plants
      {
        id: '2',
        name: 'Бархатцы',
        price: 126,
        image: '🌻',
        category: 'Indoor',
        occasion: ['Housewarming'],
        flowers: ['Marigolds'],
        rating: 4.8,
        reviewsCount: 20,
        description: 'Яркие оранжевые цветы в декоративном горшке.',
        seller: 'Радужные Розы',
        size: 'Large',
      },
      {
        id: '3',
        name: 'Цветущее растение',
        price: 246,
        image: '🌺',
        category: 'Indoor',
        occasion: ['Anniversary', 'Valentine'],
        flowers: ['Roses', 'Peonies'],
        rating: 4.9,
        reviewsCount: 25,
        description: 'Элегантное горшечное растение с темными листьями и розовыми цветами.',
        seller: 'Лилейная Аллея',
        size: 'Large',
      },
      {
        id: '4',
        name: 'Весенние цветы',
        price: 286,
        image: '🌷',
        category: 'Indoor',
        occasion: ['Housewarming', 'Birthday'],
        flowers: ['Tulips', 'Daffodils'],
        rating: 4.7,
        reviewsCount: 18,
        description: 'Свежие весенние цветы в красивом оформлении.',
        seller: 'Флорист Яков',
        size: 'Medium',
      },
      {
        id: '8',
        name: 'Лаванда',
        price: 45,
        image: '🌿',
        category: 'Indoor',
        occasion: ['Housewarming'],
        flowers: ['Lavender'],
        rating: 4.6,
        reviewsCount: 33,
        description: 'Ароматное растение лаванды, идеальное для украшения дома.',
        seller: 'Радужные Розы',
        size: 'Small',
      },
      // Vases
      {
        id: '9',
        name: 'Хрустальная ваза',
        price: 65,
        image: '🏺',
        category: 'Accessories',
        occasion: ['Wedding', 'Anniversary'],
        rating: 4.8,
        reviewsCount: 42,
        description: 'Элегантная хрустальная ваза для ваших прекрасных цветов.',
        seller: 'Флорист Яков',
        size: 'Medium',
      },
      {
        id: '10',
        name: 'Набор керамических ваз',
        price: 85,
        image: '🫖',
        category: 'Accessories',
        occasion: ['Housewarming', 'Birthday'],
        rating: 4.7,
        reviewsCount: 28,
        description: 'Набор из 3 красивых керамических ваз разных размеров.',
        seller: 'Лилейная Аллея',
        size: 'Set',
      },
      {
        id: '11',
        name: 'Современная металлическая ваза',
        price: 55,
        image: '⚱️',
        category: 'Accessories',
        occasion: ['Housewarming'],
        rating: 4.9,
        reviewsCount: 19,
        description: 'Стильная современная металлическая ваза с геометрическим дизайном.',
        seller: 'Радужные Розы',
        size: 'Large',
      },
      // Gift Cards & Messages
      {
        id: '12',
        name: 'Подарочная карта премиум',
        price: 100,
        image: '💳',
        category: 'Gifts',
        occasion: ['Birthday', 'Anniversary', 'Valentine'],
        rating: 5.0,
        reviewsCount: 156,
        description: 'Подарочная карта, которую можно использовать для любой покупки в нашем магазине.',
        seller: 'Цветочный Магазин',
        size: 'Standard',
      },
      {
        id: '13',
        name: 'Открытка ручной работы',
        price: 8,
        image: '💌',
        category: 'Gifts',
        occasion: ['Birthday', 'Anniversary', 'Valentine'],
        rating: 4.9,
        reviewsCount: 89,
        description: 'Красивая открытка ручной работы с вашим посланием.',
        seller: 'Флорист Яков',
        size: 'Standard',
      },
      {
        id: '14',
        name: 'Подарочная коробка',
        price: 25,
        image: '🎁',
        category: 'Gifts',
        occasion: ['Birthday', 'Anniversary'],
        rating: 4.8,
        reviewsCount: 67,
        description: 'Элегантная подарочная коробка с лентой и открыткой.',
        seller: 'Лилейная Аллея',
        size: 'Standard',
      },
      // Chocolates & Sweets
      {
        id: '15',
        name: 'Премиум набор шоколада',
        price: 35,
        image: '🍫',
        category: 'Gifts',
        occasion: ['Valentine', 'Birthday', 'Anniversary'],
        rating: 4.9,
        reviewsCount: 124,
        description: 'Роскошная коробка шоколада с различными вкусами.',
        seller: 'Радужные Розы',
        size: 'Medium',
      },
      {
        id: '16',
        name: 'Подарочный набор меда',
        price: 28,
        image: '🍯',
        category: 'Gifts',
        occasion: ['Housewarming', 'Birthday'],
        rating: 4.7,
        reviewsCount: 45,
        description: 'Натуральный мед в красивой подарочной упаковке.',
        seller: 'Флорист Яков',
        size: 'Small',
      },
      // Decorative Items
      {
        id: '17',
        name: 'Набор лент и бантов',
        price: 12,
        image: '🎀',
        category: 'Accessories',
        occasion: ['Wedding', 'Birthday'],
        rating: 4.6,
        reviewsCount: 38,
        description: 'Яркий набор лент и бантов для упаковки подарков.',
        seller: 'Лилейная Аллея',
        size: 'Set',
      },
      {
        id: '18',
        name: 'Набор декоративных свечей',
        price: 32,
        image: '🕯️',
        category: 'Accessories',
        occasion: ['Housewarming', 'Anniversary'],
        rating: 4.8,
        reviewsCount: 71,
        description: 'Элегантные ароматические свечи в декоративных подсвечниках.',
        seller: 'Радужные Розы',
        size: 'Set',
      },
      {
        id: '19',
        name: 'Консервант для цветов',
        price: 15,
        image: '🧪',
        category: 'Accessories',
        occasion: [],
        rating: 4.9,
        reviewsCount: 203,
        description: 'Специальный консервант для сохранения свежести цветов дольше.',
        seller: 'Флорист Яков',
        size: 'Standard',
      },
      // Soft Toys
      {
        id: '20',
        name: 'Мишка с цветами',
        price: 45,
        image: '🧸',
        category: 'Gifts',
        occasion: ['Valentine', 'Birthday'],
        rating: 4.8,
        reviewsCount: 92,
        description: 'Очаровательный плюшевый мишка с небольшим букетом цветов.',
        seller: 'Лилейная Аллея',
        size: 'Medium',
      },
      // More Bouquets
      {
        id: '21',
        name: 'Белая элегантность',
        price: 120,
        image: '🤍',
        category: 'Bouquets',
        occasion: ['Wedding', 'Funeral'],
        flowers: ['White Roses', 'Lilies'],
        rating: 4.9,
        reviewsCount: 78,
        description: 'Чистый белый элегантный букет для особых случаев.',
        seller: 'Флорист Яков',
        size: 'Large',
      },
      {
        id: '22',
        name: 'Радужная смесь',
        price: 105,
        image: '🌈',
        category: 'Bouquets',
        occasion: ['Birthday', 'Graduation'],
        flowers: ['Mixed Seasonal'],
        rating: 4.7,
        reviewsCount: 56,
        description: 'Яркая смесь сезонных цветов в сочных красках.',
        seller: 'Радужные Розы',
        size: 'Medium',
      },
      // More Bouquets
      {
        id: '23',
        name: 'Букет красных роз',
        price: 125,
        image: '🌹',
        category: 'Bouquets',
        occasion: ['Valentine', 'Anniversary'],
        flowers: ['Red Roses'],
        rating: 4.9,
        reviewsCount: 203,
        description: 'Классический букет красных роз, идеальный для выражения любви.',
        seller: 'Флорист Яков',
        size: 'Large',
      },
      {
        id: '24',
        name: 'Букет лилий',
        price: 98,
        image: '🌺',
        category: 'Bouquets',
        occasion: ['Wedding', 'Anniversary'],
        flowers: ['Lilies', 'Baby Breath'],
        rating: 4.8,
        reviewsCount: 91,
        description: 'Элегантные белые лилии с акцентами из гипсофилы.',
        seller: 'Лилейная Аллея',
        size: 'Medium',
      },
      {
        id: '25',
        name: 'Весенний микс тюльпанов',
        price: 75,
        image: '🌷',
        category: 'Bouquets',
        occasion: ['Birthday', 'Housewarming'],
        flowers: ['Tulips'],
        rating: 4.7,
        reviewsCount: 64,
        description: 'Свежие весенние тюльпаны различных цветов.',
        seller: 'Радужные Розы',
        size: 'Medium',
      },
      // More Indoor Plants
      {
        id: '26',
        name: 'Сад суккулентов',
        price: 35,
        image: '🌵',
        category: 'Indoor',
        occasion: ['Housewarming'],
        flowers: ['Succulents'],
        rating: 4.8,
        reviewsCount: 127,
        description: 'Красивая композиция из суккулентов в декоративном горшке.',
        seller: 'Лилейная Аллея',
        size: 'Small',
      },
      {
        id: '27',
        name: 'Орхидея',
        price: 68,
        image: '🪷',
        category: 'Indoor',
        occasion: ['Anniversary', 'Housewarming'],
        flowers: ['Orchids'],
        rating: 4.9,
        reviewsCount: 88,
        description: 'Элегантное растение орхидеи в керамическом горшке.',
        seller: 'Флорист Яков',
        size: 'Medium',
      },
      {
        id: '28',
        name: 'Бамбук',
        price: 42,
        image: '🎋',
        category: 'Indoor',
        occasion: ['Housewarming'],
        flowers: ['Bamboo'],
        rating: 4.6,
        reviewsCount: 45,
        description: 'Бамбук удачи для привлечения благополучия.',
        seller: 'Радужные Розы',
        size: 'Medium',
      },
      // More Accessories
      {
        id: '29',
        name: 'Набор для составления букетов',
        price: 45,
        image: '🧰',
        category: 'Accessories',
        occasion: ['Birthday'],
        rating: 4.7,
        reviewsCount: 56,
        description: 'Полный набор для создания собственных композиций.',
        seller: 'Лилейная Аллея',
        size: 'Set',
      },
      {
        id: '30',
        name: 'Лейка декоративная',
        price: 28,
        image: '🚿',
        category: 'Accessories',
        occasion: [],
        rating: 4.8,
        reviewsCount: 73,
        description: 'Декоративная лейка для ваших растений.',
        seller: 'Флорист Яков',
        size: 'Standard',
      },
      {
        id: '31',
        name: 'Подставка для растений',
        price: 55,
        image: '🪑',
        category: 'Accessories',
        occasion: ['Housewarming'],
        rating: 4.6,
        reviewsCount: 39,
        description: 'Современная подставка для комнатных растений.',
        seller: 'Радужные Розы',
        size: 'Large',
      },
      // More Gifts
      {
        id: '32',
        name: 'Набор цветочных горшков',
        price: 38,
        image: '🪴',
        category: 'Gifts',
        occasion: ['Housewarming', 'Birthday'],
        rating: 4.8,
        reviewsCount: 102,
        description: 'Набор из 3 декоративных цветочных горшков.',
        seller: 'Лилейная Аллея',
        size: 'Set',
      },
      {
        id: '33',
        name: 'Ароматическая свеча с цветочным ароматом',
        price: 22,
        image: '🕯️',
        category: 'Gifts',
        occasion: ['Anniversary', 'Birthday'],
        rating: 4.9,
        reviewsCount: 145,
        description: 'Роскошная ароматическая свеча с цветочным ароматом.',
        seller: 'Радужные Розы',
        size: 'Standard',
      },
      {
        id: '34',
        name: 'Услуга упаковки подарка',
        price: 15,
        image: '🎀',
        category: 'Gifts',
        occasion: ['Birthday', 'Anniversary', 'Valentine'],
        rating: 5.0,
        reviewsCount: 234,
        description: 'Профессиональная упаковка подарка с лентой и открыткой.',
        seller: 'Флорист Яков',
        size: 'Standard',
      },
      // New Products
      {
        id: '35',
        name: 'Букет сакуры',
        price: 115,
        image: '🌸',
        category: 'Bouquets',
        occasion: ['Spring', 'Anniversary', 'Birthday'],
        flowers: ['Cherry Blossoms'],
        rating: 4.9,
        reviewsCount: 67,
        description: 'Нежный букет сакуры, идеальный для весенних праздников.',
        seller: 'Радужные Розы',
        size: 'Medium',
      },
      {
        id: '36',
        name: 'Поле подсолнухов',
        price: 88,
        image: '🌻',
        category: 'Bouquets',
        occasion: ['Birthday', 'Graduation', 'Housewarming'],
        flowers: ['Sunflowers'],
        rating: 4.8,
        reviewsCount: 94,
        description: 'Яркая и жизнерадостная композиция из подсолнухов.',
        seller: 'Лилейная Аллея',
        size: 'Large',
      },
      {
        id: '37',
        name: 'Композиция из лотосов',
        price: 125,
        image: '🪷',
        category: 'Bouquets',
        occasion: ['Wedding', 'Anniversary'],
        flowers: ['Lotus'],
        rating: 4.9,
        reviewsCount: 43,
        description: 'Элегантная композиция из цветов лотоса для особых случаев.',
        seller: 'Флорист Яков',
        size: 'Large',
      },
      {
        id: '38',
        name: 'Коллекция кактусов',
        price: 48,
        image: '🌵',
        category: 'Indoor',
        occasion: ['Housewarming'],
        flowers: ['Cacti'],
        rating: 4.7,
        reviewsCount: 156,
        description: 'Красивая коллекция декоративных кактусов в современных горшках.',
        seller: 'Лилейная Аллея',
        size: 'Set',
      },
      {
        id: '39',
        name: 'Горшечное растение',
        price: 38,
        image: '🪴',
        category: 'Indoor',
        occasion: ['Housewarming', 'Birthday'],
        flowers: ['House Plants'],
        rating: 4.8,
        reviewsCount: 112,
        description: 'Здоровое горшечное растение, идеальное для украшения дома.',
        seller: 'Радужные Розы',
        size: 'Medium',
      },
      {
        id: '40',
        name: 'Бамбук удачи',
        price: 42,
        image: '🎋',
        category: 'Indoor',
        occasion: ['Housewarming', 'New Year'],
        flowers: ['Bamboo'],
        rating: 4.6,
        reviewsCount: 89,
        description: 'Традиционное растение бамбука удачи для привлечения благополучия.',
        seller: 'Флорист Яков',
        size: 'Medium',
      },
      {
        id: '41',
        name: 'Набор трав для сада',
        price: 55,
        image: '🌿',
        category: 'Indoor',
        occasion: ['Housewarming', 'Birthday'],
        flowers: ['Herbs'],
        rating: 4.9,
        reviewsCount: 134,
        description: 'Свежий набор трав для сада с базиликом, мятой и розмарином.',
        seller: 'Лилейная Аллея',
        size: 'Set',
      },
      {
        id: '42',
        name: 'Набор цветочных духов',
        price: 65,
        image: '🌺',
        category: 'Gifts',
        occasion: ['Valentine', 'Anniversary', 'Birthday'],
        rating: 4.8,
        reviewsCount: 178,
        description: 'Роскошный набор цветочных духов с тремя ароматами.',
        seller: 'Радужные Розы',
        size: 'Set',
      },
      {
        id: '43',
        name: 'Набор для ванны с лепестками роз',
        price: 45,
        image: '🌹',
        category: 'Gifts',
        occasion: ['Valentine', 'Anniversary'],
        rating: 4.9,
        reviewsCount: 201,
        description: 'Роскошный набор для ванны с лепестками роз для релаксации.',
        seller: 'Флорист Яков',
        size: 'Set',
      },
      {
        id: '44',
        name: 'Коллекция цветочного чая',
        price: 32,
        image: '🫖',
        category: 'Gifts',
        occasion: ['Birthday', 'Housewarming'],
        rating: 4.7,
        reviewsCount: 98,
        description: 'Премиум коллекция цветочного чая с различными вкусами.',
        seller: 'Лилейная Аллея',
        size: 'Set',
      },
      {
        id: '45',
        name: 'Набор садовых инструментов',
        price: 75,
        image: '🧰',
        category: 'Accessories',
        occasion: ['Housewarming', 'Birthday'],
        rating: 4.8,
        reviewsCount: 76,
        description: 'Полный набор садовых инструментов для ухода за растениями.',
        seller: 'Радужные Розы',
        size: 'Set',
      },
      {
        id: '46',
        name: 'Декоративная подвеска для растений',
        price: 28,
        image: '🪑',
        category: 'Accessories',
        occasion: ['Housewarming'],
        rating: 4.6,
        reviewsCount: 54,
        description: 'Современная декоративная подвеска для комнатных растений.',
        seller: 'Флорист Яков',
        size: 'Standard',
      },
      {
        id: '47',
        name: 'Аромадиффузор с цветочным ароматом',
        price: 38,
        image: '🕯️',
        category: 'Accessories',
        occasion: ['Housewarming', 'Anniversary'],
        rating: 4.9,
        reviewsCount: 167,
        description: 'Элегантный аромадиффузор с цветочным ароматом для домашней атмосферы.',
        seller: 'Лилейная Аллея',
        size: 'Standard',
      },
      {
        id: '48',
        name: 'Белый букет в форме сердца',
        price: 105,
        image: '🤍',
        category: 'Bouquets',
        occasion: ['Wedding', 'Anniversary', 'Valentine'],
        flowers: ['White Roses', 'Baby Breath'],
        rating: 4.9,
        reviewsCount: 145,
        description: 'Чистый белый букет в форме сердца для особых моментов.',
        seller: 'Радужные Розы',
        size: 'Medium',
      },
      {
        id: '49',
        name: 'Радужный смешанный букет',
        price: 95,
        image: '🌈',
        category: 'Bouquets',
        occasion: ['Birthday', 'Graduation', 'Celebration'],
        flowers: ['Mixed Seasonal'],
        rating: 4.8,
        reviewsCount: 123,
        description: 'Яркая радужная смесь красочных сезонных цветов.',
        seller: 'Флорист Яков',
        size: 'Large',
      },
      {
        id: '50',
        name: 'Премиум семена цветов',
        price: 18,
        image: '🌱',
        category: 'Gifts',
        occasion: ['Housewarming', 'Birthday'],
        rating: 4.7,
        reviewsCount: 87,
        description: 'Премиум коллекция семян цветов для садоводов-энтузиастов.',
        seller: 'Лилейная Аллея',
        size: 'Set',
      },
      // Новые букеты
      {
        id: '51',
        name: 'Розовый пион букет',
        price: 135,
        image: '🌸',
        category: 'Bouquets',
        occasion: ['Wedding', 'Anniversary', 'Birthday'],
        flowers: ['Peonies', 'Roses'],
        rating: 4.9,
        reviewsCount: 156,
        description: 'Роскошный букет из пионов и роз в нежных розовых тонах.',
        seller: 'Флорист Яков',
        size: 'Large',
      },
      {
        id: '52',
        name: 'Лавандовый букет',
        price: 92,
        image: '💜',
        category: 'Bouquets',
        occasion: ['Anniversary', 'Birthday'],
        flowers: ['Lavender', 'Eucalyptus'],
        rating: 4.8,
        reviewsCount: 89,
        description: 'Ароматный букет из лаванды с эвкалиптом.',
        seller: 'Радужные Розы',
        size: 'Medium',
      },
      {
        id: '53',
        name: 'Желтый подсолнух букет',
        price: 78,
        image: '🌻',
        category: 'Bouquets',
        occasion: ['Birthday', 'Graduation'],
        flowers: ['Sunflowers'],
        rating: 4.7,
        reviewsCount: 112,
        description: 'Яркий букет из подсолнухов для поднятия настроения.',
        seller: 'Лилейная Аллея',
        size: 'Medium',
      },
      {
        id: '54',
        name: 'Белые хризантемы',
        price: 85,
        image: '🌼',
        category: 'Bouquets',
        occasion: ['Funeral', 'Wedding'],
        flowers: ['Chrysanthemums'],
        rating: 4.8,
        reviewsCount: 67,
        description: 'Элегантный букет из белых хризантем.',
        seller: 'Флорист Яков',
        size: 'Medium',
      },
      {
        id: '55',
        name: 'Красные гвоздики',
        price: 65,
        image: '🌺',
        category: 'Bouquets',
        occasion: ['Birthday', 'Anniversary'],
        flowers: ['Carnations'],
        rating: 4.6,
        reviewsCount: 94,
        description: 'Классический букет из красных гвоздик.',
        seller: 'Радужные Розы',
        size: 'Small',
      },
      // Новые комнатные растения
      {
        id: '56',
        name: 'Фикус Бенджамина',
        price: 580,
        image: '🌳',
        category: 'Indoor',
        occasion: ['Housewarming'],
        flowers: ['Ficus'],
        rating: 4.9,
        reviewsCount: 234,
        description: 'Популярное комнатное дерево с глянцевыми листьями.',
        seller: 'Лилейная Аллея',
        size: 'Large',
      },
      {
        id: '57',
        name: 'Монстера',
        price: 420,
        image: '🌿',
        category: 'Indoor',
        occasion: ['Housewarming', 'Birthday'],
        flowers: ['Monstera'],
        rating: 4.8,
        reviewsCount: 189,
        description: 'Тропическое растение с резными листьями.',
        seller: 'Флорист Яков',
        size: 'Large',
      },
      {
        id: '58',
        name: 'Алоэ Вера',
        price: 180,
        image: '🌱',
        category: 'Indoor',
        occasion: ['Housewarming'],
        flowers: ['Aloe'],
        rating: 4.7,
        reviewsCount: 145,
        description: 'Лечебное растение с полезными свойствами.',
        seller: 'Радужные Розы',
        size: 'Medium',
      },
      {
        id: '59',
        name: 'Спатифиллум',
        price: 320,
        image: '🪴',
        category: 'Indoor',
        occasion: ['Housewarming', 'Anniversary'],
        flowers: ['Peace Lily'],
        rating: 4.9,
        reviewsCount: 201,
        description: 'Элегантное растение с белыми цветами.',
        seller: 'Лилейная Аллея',
        size: 'Medium',
      },
      {
        id: '60',
        name: 'Драцена',
        price: 380,
        image: '🌴',
        category: 'Indoor',
        occasion: ['Housewarming'],
        flowers: ['Dracaena'],
        rating: 4.8,
        reviewsCount: 167,
        description: 'Декоративное растение с длинными листьями.',
        seller: 'Флорист Яков',
        size: 'Large',
      },
      // Новые подарки
      {
        id: '61',
        name: 'Подарочный набор с конфетами',
        price: 550,
        image: '🍬',
        category: 'Gifts',
        occasion: ['Valentine', 'Birthday', 'Anniversary'],
        rating: 4.9,
        reviewsCount: 278,
        description: 'Роскошный набор: букет цветов и премиум конфеты.',
        seller: 'Радужные Розы',
        size: 'Set',
      },
      {
        id: '62',
        name: 'Подарочный сертификат',
        price: 500,
        image: '🎟️',
        category: 'Gifts',
        occasion: ['Birthday', 'Anniversary', 'Valentine'],
        rating: 5.0,
        reviewsCount: 312,
        description: 'Сертификат на любую сумму для выбора подарка.',
        seller: 'Цветочный Магазин',
        size: 'Standard',
      },
      {
        id: '63',
        name: 'Мягкая игрушка с цветами',
        price: 680,
        image: '🐻',
        category: 'Gifts',
        occasion: ['Valentine', 'Birthday'],
        rating: 4.8,
        reviewsCount: 156,
        description: 'Большой плюшевый мишка с букетом цветов.',
        seller: 'Лилейная Аллея',
        size: 'Large',
      },
      {
        id: '64',
        name: 'Подарочная корзина',
        price: 1200,
        image: '🧺',
        category: 'Gifts',
        occasion: ['Birthday', 'Anniversary', 'Housewarming'],
        rating: 4.9,
        reviewsCount: 198,
        description: 'Корзина с цветами, конфетами и открыткой.',
        seller: 'Флорист Яков',
        size: 'Set',
      },
      {
        id: '65',
        name: 'Шоколадный набор',
        price: 450,
        image: '🍫',
        category: 'Gifts',
        occasion: ['Valentine', 'Birthday', 'Anniversary'],
        rating: 4.9,
        reviewsCount: 267,
        description: 'Премиум шоколад ручной работы в красивой упаковке.',
        seller: 'Радужные Розы',
        size: 'Set',
      },
      // Новые аксессуары
      {
        id: '66',
        name: 'Высокая стеклянная ваза',
        price: 320,
        image: '🏺',
        category: 'Accessories',
        occasion: ['Wedding', 'Anniversary', 'Housewarming'],
        rating: 4.8,
        reviewsCount: 134,
        description: 'Высокая прозрачная ваза для больших букетов.',
        seller: 'Флорист Яков',
        size: 'Large',
      },
      {
        id: '67',
        name: 'Керамическая ваза',
        price: 280,
        image: '🫖',
        category: 'Accessories',
        occasion: ['Housewarming', 'Birthday'],
        rating: 4.7,
        reviewsCount: 98,
        description: 'Стильная керамическая ваза ручной работы.',
        seller: 'Лилейная Аллея',
        size: 'Medium',
      },
      {
        id: '68',
        name: 'Удобрение для цветов',
        price: 95,
        image: '🧪',
        category: 'Accessories',
        occasion: [],
        rating: 4.9,
        reviewsCount: 423,
        description: 'Комплексное удобрение для комнатных растений.',
        seller: 'Радужные Розы',
        size: 'Standard',
      },
      {
        id: '69',
        name: 'Опрыскиватель для растений',
        price: 180,
        image: '💧',
        category: 'Accessories',
        occasion: [],
        rating: 4.7,
        reviewsCount: 156,
        description: 'Удобный опрыскиватель для ухода за растениями.',
        seller: 'Флорист Яков',
        size: 'Standard',
      },
      {
        id: '70',
        name: 'Набор декоративных горшков',
        price: 420,
        image: '🪴',
        category: 'Accessories',
        occasion: ['Housewarming', 'Birthday'],
        rating: 4.8,
        reviewsCount: 189,
        description: 'Набор из 3 декоративных горшков разных размеров.',
        seller: 'Лилейная Аллея',
        size: 'Set',
      },
      // Новые категории - Семена
      {
        id: '71',
        name: 'Семена роз',
        price: 45,
        image: '🌹',
        category: 'Seeds',
        occasion: ['Housewarming', 'Birthday'],
        rating: 4.6,
        reviewsCount: 78,
        description: 'Семена роз различных сортов для выращивания.',
        seller: 'Радужные Розы',
        size: 'Standard',
      },
      {
        id: '72',
        name: 'Луковицы тюльпанов',
        price: 35,
        image: '🌷',
        category: 'Seeds',
        occasion: ['Housewarming'],
        rating: 4.7,
        reviewsCount: 112,
        description: 'Луковицы тюльпанов для весенней посадки.',
        seller: 'Флорист Яков',
        size: 'Set',
      },
      {
        id: '73',
        name: 'Семена подсолнухов',
        price: 28,
        image: '🌻',
        category: 'Seeds',
        occasion: ['Housewarming'],
        rating: 4.8,
        reviewsCount: 145,
        description: 'Семена подсолнухов для сада или балкона.',
        seller: 'Лилейная Аллея',
        size: 'Standard',
      },
      // Новые категории - Уход
      {
        id: '74',
        name: 'Набор для ухода за цветами',
        price: 580,
        image: '🧰',
        category: 'Care',
        occasion: ['Housewarming', 'Birthday'],
        rating: 4.9,
        reviewsCount: 234,
        description: 'Полный набор инструментов для ухода за растениями.',
        seller: 'Радужные Розы',
        size: 'Set',
      },
      {
        id: '75',
        name: 'Грунт для комнатных растений',
        price: 120,
        image: '🌍',
        category: 'Care',
        occasion: [],
        rating: 4.8,
        reviewsCount: 312,
        description: 'Специальная почвенная смесь для комнатных растений.',
        seller: 'Флорист Яков',
        size: 'Standard',
      },
      {
        id: '76',
        name: 'Дренаж для горшков',
        price: 65,
        image: '🪨',
        category: 'Care',
        occasion: [],
        rating: 4.7,
        reviewsCount: 189,
        description: 'Керамзит для дренажа в цветочных горшках.',
        seller: 'Лилейная Аллея',
        size: 'Standard',
      },
      // Дополнительные букеты
      {
        id: '77',
        name: 'Букет невесты',
        price: 850,
        image: '💐',
        category: 'Bouquets',
        occasion: ['Wedding'],
        flowers: ['White Roses', 'Lilies', 'Baby Breath'],
        rating: 5.0,
        reviewsCount: 89,
        description: 'Роскошный букет невесты из белых роз и лилий.',
        seller: 'Флорист Яков',
        size: 'Large',
      },
      {
        id: '78',
        name: 'Букет на 8 марта',
        price: 650,
        image: '🌷',
        category: 'Bouquets',
        occasion: ['International Women\'s Day'],
        flowers: ['Tulips', 'Mimosa'],
        rating: 4.9,
        reviewsCount: 456,
        description: 'Праздничный букет из тюльпанов и мимозы.',
        seller: 'Радужные Розы',
        size: 'Large',
      },
      {
        id: '79',
        name: 'Букет на день рождения',
        price: 480,
        image: '🎂',
        category: 'Bouquets',
        occasion: ['Birthday'],
        flowers: ['Mixed Seasonal'],
        rating: 4.8,
        reviewsCount: 278,
        description: 'Яркий праздничный букет для именинника.',
        seller: 'Лилейная Аллея',
        size: 'Medium',
      },
      {
        id: '80',
        name: 'Букет из полевых цветов',
        price: 320,
        image: '🌾',
        category: 'Bouquets',
        occasion: ['Birthday', 'Housewarming'],
        flowers: ['Wildflowers'],
        rating: 4.7,
        reviewsCount: 134,
        description: 'Романтичный букет из полевых цветов.',
        seller: 'Флорист Яков',
        size: 'Medium',
      },
    ]
    
    localStorage.setItem(STORAGE_KEYS.PRODUCTS, JSON.stringify(mockProducts))
    localStorage.setItem('flowers_products_version', '4')
    return mockProducts
  },

  // Reviews
  getReviews: (productId?: string): Review[] => {
    if (typeof window === 'undefined') return []
    const data = localStorage.getItem(STORAGE_KEYS.REVIEWS)
    const reviews: Review[] = data ? JSON.parse(data) : []
    return productId ? reviews.filter((r) => r.productId === productId) : reviews
  },

  addReview: (review: Review): void => {
    const reviews = storage.getReviews()
    reviews.unshift(review)
    localStorage.setItem(STORAGE_KEYS.REVIEWS, JSON.stringify(reviews))
  },
}

